apiVersion: v2
description: A Helm chart for the Rainbows as a Service App
name: rainbows-as-a-service
version: 0.1.0
type: application
icon: https://salaboy.files.wordpress.com/2019/07/avatar.png
appVersion: 0.1.0
maintainers: 
  - name: salaboy
    email: salaboy@gmail.com
    url: http://salaboy.com
home: http://github.com/salaboy/from-monolith-to-k8s    
keywords:
  - cloudnative
  - example
  - kubecon
  - kubernetes
  - tutorial